### ISSUE TITLE
Iterates active nodes of a tree buffer.

### ISSUE THREAD

**Issue by ziqingluo** [rgrig/treebuffers#1]
For a just initialized tree buffer t,  t->active is a "fake" node whose most fields are uninitialized.

If I attempt to iterate over all active nodes on t using the following code :
`for (Node * n = tb_active(t); n; n = tb_next_active(t, n)) { ... }`
it will be incorrect since n is required to be active but actually it is the "fake" node.

**Comment by rgrig** [comment]
`tb_active()` does not return `t->active`, but `t->active->rl`
so, the code above should work.

reopen if you think that's wrong
